# name: CI

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2

#     - name: Run a one-line script
#       run: echo Hellow, world!

#     - name: Run a multi-line script
#       run:
#         echo Add other actions to build
#         test, and deploy your project.

# .github/workflows/**main.yml**

name: Django-app workflow

on: [push]

jobs:
  # Тесты
  tests:
    # «Раннер» — создание изолированного окружения с последней версией Ubuntu 
    runs-on: ubuntu-latest

    steps:
    # Запуск actions checkout — готового скрипта 
    # для клонирования репозитория
    - uses: actions/checkout@v2
    - name: Set up Python
      # Запуск actions setup-python — готового скрипта 
      # для развёртывания окружения Python
      uses: actions/setup-python@v2
      with:
        # Выбор версии Python
        python-version: 3.7

    - name: Install dependencies
      run: | 
        # обновление pip
        python -m pip install --upgrade pip 
        # установка flake8 и его плагинов
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        # установка зависимостей
        pip install -r requirements.txt 

    - name: Test with flake8 and django tests
      run: |
        # запуск проверки проекта по flake8
        python -m flake8
        # перейти в папку, содержащую manage.py — 
        #<корневая_папка_infra_actions>/<папка_проекта>/manage.py
        cd infra_project/
        # запустить написанные разработчиком тесты
        python manage.py test

  # Сборка и отправка образа на Docker_Hub
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests # Эта задача запуститься только после успешного выполнения tests
    steps:
      - name: Check out the repo
        # Проверка доступности репозитория Docker Hub для workflow
        uses: actions/checkout@v2 
      - name: Set up Docker Buildx
        # Вызов сборщика контейнеров docker
        uses: docker/setup-buildx-action@v1 
      - name: Login to Docker 
        # Запуск скрипта авторизации на Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        # Пуш образа в Docker Hub 
        uses: docker/build-push-action@v2 
        with:
          push: true
          tags: wests007/infra_actions_project:latest

  # Деплой образа из Docker_Hub на сервер Яндекс.Облако
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        #key: ${{ secrets.SSH_KEY }}
        key: b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABBkC/5yP/5qKeQkD9bCt6YmAAAAEAAAAAEAAAGXAAAAB3NzaC1yc2EAAAADAQABAAABgQCqRGHR3eE1i6loGGtVypef1Hnzw/rIFoaQbHKFEQzVmsdcoVGfobpqNIiSQYzWBzQZKyMLxCDl8VoqD/LezRYkooeOBAY/YeYz9eQDrVpTCCY4NG/AhIxrt9DGl4K1m0Rpewr5nzQFesGF7NBzbsNMfvucyJGjFlJh+V7SM4/PSZEOqoyptEZbSX4zKhseCfDCGYEvGxlweRruUq8WQEzBhj0bv0yDFRJ3lTheUp2UZZ62qpzMetO3riwDy7H+JyFdcvGvvablikRfGZC+JGTrdD4B3u8FFbE7O4ip7kdkmABQm1YujigxW0D2g5X10Pe3TtxXnhtnWaNgg3fBCOyuENL1B9Oi48q5MIvwE/EaTqvFbOxPZTU/rAF7GfUf08Gf1FYCShaWLmKQY5zoCOSqllLZq+CWL6qel7Ua+rA0oEwmi55Wgg5C+9t2jRHacRQQzNlweFNHN80t2rwfs+f8eSgQl8oBuekSiaLnwoqlYFrxXvCf0zNrc0dSd4qo3HEAAAWALM+sv/2spII32+nikqeaEkwu+hfdzsvpAhP/PyWgR8hf6o06H8TKg7SKFbOcGnpv1rzBRAWy4cShBFHmyNCcPKKGcpWnoKiwUeCXR+QK95NpFN3zDCCAv9vKLzl6JcmY6Qah4vpXx2A3HZM3XithswxbmjlTQIHNqq7PjlIeccKUr9R9KsoJxHEOxXGB8yhYDdQMY1ZUDc41lbFghr7PFuUPk7SMzK2cNZcg2zgxl68q/jOukBYXGyKyL1mgC0MAlbnwDgsHmuk+q95fW4RaLFn+eabyC4NU3tEhieZ44guBPMb81H0GqBdrRPQRQsUzgdfhfiLcb+Q6zq0t9Ea7yxGTwWV36FmmF4oHUGuQ/2KSmIQaXLnMv699txFrIgC1iB/ggCDsLI2mrtY63o2wDqPRljXIrH5xrJAAVl7TxzC7IB7ckFXpAeKX/Au4U/j4Gk78KQRP2Q308pLkrD/w3JoOO+HFy+lOMORTyn0os2Aq9oB71cyqKKxllx5o8FRwEf/D/EtxfZd1hpKUrXYSuUIHgevWJ2eOnd9gZE/jOgNsqV5Z0T7IMe8DkMlZa1g5llYU7IbIqJHOs+TfC09K/fcFtP7Do2EJsd5VINJ4UkD+nCJ4sUbz7MZF4IZXldhc/Al8ilfbi0PjhuybexU7GpXGyrQtwKjTMJDQRJ99a/pqeoG/JR3w4+QVOS0W4uKHKweZy+qGsvaQsGcumGtFwnnGcmTMRYjxnjcFr2PIvyp81zgQcsiAewi+Gvk6GJOD7rpFuTQ5ySK7eC1BIZSLgu8ToHSjjQHijVtotQOBJ0HhhruFEbt939KWXL5DqH7BUFammKIstMKvu4mFLbNI8WCH3C8GNYOTviSU+C28OcugMIZCmgojIWCJitiQeTSrOTC3J2r9xhuLf1HESsbY3lms3xoz/xBqOvj+HJdodBsJbayoQqK1/W5gxfgnqb/UarR5Pg5XeJiYHb7vnsCi5fpShPkrDB+0dJfbEs+nfz4Rmfvr/jhQf4kBfQ5QbBOshUhsRnd0iW3W17tNZ1ULCD5BPTp66Ckz9ghuOysUGxx0MybdAI99VMi4ZiKS1l7pLtWRiuRDda3J/lvObN5gDBH+inVXpKxPi2uwI/sKFmDRa4+6C5VMuhclWaREvV3ZwrT0jg5Zu9RplNxRZHTRWhvneAfzNbeFqWw7mPiPIg4uwQ370H84owW357vfyQxfvwBr/kPL4K3+QfAiON1xmNUIeGjqAq8NglBNXWlX20j71gHREprmEpT06Mxy0hCkK45iM2+0m3Lb7tMt50y9BqBasEyt1G3GDbyhj4YrdUFRper+91GNrR0WsH/6XdyFgHsF650kn8368k/g19NW/+0uR+p7BHEtYYa4Vfn8e1JUbz6/za8qXewanEwa9glzvKiNsEnS6h64jwM8ij2RisIPnZOw0SzYScbx3u4H7RLNmD0MBPdueXakBR+OubrNBRCtWf04yOagRwyH/HMfMiXuSi6TlxELI7j72i7n2kbzNEjYCRLj5PnleLvnziUHmQfndQf92q1hfsxvQRLEDLWyGcuKyE13B/Ga3nE0mi4oFOhCQPNSFOz75OfEE8pugDLlIYS7EtJaaZev8XZXOGWFDYwRJDCkPUePNaBZVXu90OvzXUqJ9GpuaJ3NcwJwg+tEGKtSVC9PE5dvcqonjiyjishDuuwId6Q1KUQVnlGVFPNXWwVX/8K2HHi4DCRXBd9qVpuwXLyeo+njlQcq1mVCvHB+ogL3IBDG+fipytb3cXhnxdQECpdi5uv3wDUDpehqadUPykNLieUGZv6iE+5jqf9Ujnw017TezppT/CovGj4qsvFqFZHN3fM6GV83/H863Nf5X7WQy3RqEJvJcA==
        passphrase: ${{ secrets.PASSPHRASE }} # Если ваш ssh-ключ защищён фразой-паролем
        script: |
          # Выполняет pull образа с DockerHub
          sudo docker pull wests007/infra_actions_project
          #остановка всех контейнеров
          sudo docker stop $(sudo docker ps -a -q)
          sudo docker run --rm -d -p 5000:5000 wests007/infra_actions_project

